spring.application.name=ChatService
server.port=${PORT:8080}
#redis configuration
spring.data.redis.url=${REDIS_URL}
spring.data.redis.ssl.enabled=true
#database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size = 5
#CORS configuration
app.cors.allowed-origins=${ALLOWED_ORIGINS}
